/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fajlbololvasasesmentes;

import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import static java.nio.file.Files.readAllLines;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Varadi.Akos
 */
public class Adatok extends javax.swing.JFrame {

    /**
     * Creates new form Adatok
     */
    private ArrayList<Ember> emberosztaly;

    public Adatok() {
        initComponents();
        jFileChooser1.showOpenDialog(jPanel1);
        jFileChooser1.getSelectedFile();
        jFileChooser1.getCurrentDirectory();
        jTextField1.setText(jFileChooser1.getSelectedFile().toString());
        jTextField2.setText(jFileChooser1.getCurrentDirectory().toString());
        try {
            List<String> lista = Files.readAllLines(Paths.get(jFileChooser1.getSelectedFile().toString()));
//            List<String> lista=Files.readAllLines("ember.txt");
            emberosztaly = new ArrayList<>();
            for (int i = 0; i < lista.size(); i++) {
                String egySor = lista.get(i);
                String[] adatok = egySor.split(";");
                if (!adatok[0].equals("NÉV")) {
                    if (adatok.length == 3) {
                        Ember e = new Ember(adatok[0], Integer.parseInt(adatok[1]), adatok[2]);
                        emberosztaly.add(e);
                        //emberosztaly.add(new Ember(adatok[0], Integer.parseInt(adatok[1]),adatok[2]));
                    } else {
                        Ember e = new Ember(adatok[0], Integer.parseInt(adatok[1]), adatok[2], Integer.parseInt(adatok[3]));
                        emberosztaly.add(e);
                    }
                }

            }

            for (int i = 0; i < emberosztaly.size(); i++) {
                if (emberosztaly.get(i).getNem().equals("F")) {
                    jCBFiuk.addItem(emberosztaly.get(i).getNev());
                } else {
                    jCBLanyok.addItem(emberosztaly.get(i).getNev());
                }
            }

        } catch (IOException ex) {
            Logger.getLogger(Adatok.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jFileChooser1 = new javax.swing.JFileChooser();
        jCBMindkettoNem = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jRBL = new javax.swing.JRadioButton();
        jRBF = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLLegidosebb = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLOsszKor = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLMiotaDolgozik = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLKor = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLDolgozik = new javax.swing.JLabel();
        jCBLanyok = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jCBFiuk = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCBMindkettoNem.setText("Mindketto Nem");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Összesítő"));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroup1.add(jRBL);
        jRBL.setLabel("Lány");
        jRBL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBLActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBF);
        jRBF.setText("Fiú");
        jRBF.setActionCommand("");
        jRBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBFActionPerformed(evt);
            }
        });

        jLabel1.setText("Legidősebb");

        jLLegidosebb.setText("    ");

        jLabel3.setText("Összes Kor");

        jLOsszKor.setText("     ");

        jLabel5.setText("6 Éve Dolgozó");

        jLMiotaDolgozik.setText("   ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRBF))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(48, 48, 48)
                                .addComponent(jLLegidosebb))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLOsszKor))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLMiotaDolgozik)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBL)
                    .addComponent(jRBF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLLegidosebb))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLOsszKor))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLMiotaDolgozik))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jRBL.getAccessibleContext().setAccessibleName("jRBLany");
        jRBF.getAccessibleContext().setAccessibleName("jRBFiu");
        jLabel1.getAccessibleContext().setAccessibleName("jLLegidosebb");
        jLLegidosebb.getAccessibleContext().setAccessibleName("jLLegidosebbAdat");
        jLabel3.getAccessibleContext().setAccessibleName("jLOsszesKor");
        jLOsszKor.getAccessibleContext().setAccessibleName("jLOsszesKorAdat");
        jLabel5.getAccessibleContext().setAccessibleName("jL6EveDoldozo");
        jLMiotaDolgozik.getAccessibleContext().setAccessibleName("jL6EveDoldozoAdat");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Adatok"));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setText("Kor");

        jLKor.setText("jLabel8");

        jLabel9.setText("Mióta Dolgozik");
        jLabel9.setRequestFocusEnabled(false);

        jLDolgozik.setText("jLabel10");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLKor))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLDolgozik)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLKor))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLDolgozik))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel7.getAccessibleContext().setAccessibleName("jLKor");
        jLKor.getAccessibleContext().setAccessibleName("jLKorAdat");
        jLabel9.getAccessibleContext().setAccessibleName("jLMiotaDolgozik");
        jLDolgozik.getAccessibleContext().setAccessibleName("jLMiotaDolgozikAdat");

        jCBLanyok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBLanyokActionPerformed(evt);
            }
        });

        jButton1.setLabel("Mentés");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCBFiuk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jCBFiuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBFiukActionPerformed(evt);
            }
        });

        jLabel11.setText("Lányok");

        jLabel12.setText("Fiúk");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1)
                                    .addComponent(jCBMindkettoNem)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCBLanyok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBFiuk, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBLanyok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBFiuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBMindkettoNem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jCBMindkettoNem.getAccessibleContext().setAccessibleName("jCBMindkettoNem");
        jCBLanyok.getAccessibleContext().setAccessibleName("");
        jButton1.getAccessibleContext().setAccessibleName("jBMentes");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBLanyokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBLanyokActionPerformed
        nevKereses(jCBLanyok.getSelectedItem().toString());
    }//GEN-LAST:event_jCBLanyokActionPerformed

    private String mentettAdatok="";
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
mentettAdatok="";
        if(jCBMindkettoNem.isSelected()){
                mentettAdatok+="Lányok:\n";
//                jLLegidosebb.setText(String.valueOf(legidosebb("L")));
//                jLOsszKor.setText(String.valueOf(evekOsszegzese("L")));
//                jLMiotaDolgozik.setText(String.valueOf(kereses("L")));

//                mentettAdatok+="legidősebb:"+jLLegidosebb.getText()+" éves\n";
//                mentettAdatok+="ÖsszesKor"+jLOsszKor.getText()+" ev\n";
//                mentettAdatok+="6 éve dolgozó:"+jLMiotaDolgozik.getText();
//                
//                mentettAdatok+="legidősebb:"+legidosebb("L")+" éves\n";
//                mentettAdatok+="ÖsszesKor"+evekOsszegzese("L")+" ev\n";
//                mentettAdatok+="6 éve dolgozó:"+kereses("L");
adatKiiras("L");
                mentettAdatok+="\n";
                mentettAdatok+="Fiuk:\n";
//                jLLegidosebb.setText(String.valueOf(legidosebb("F"))); 
//                jLOsszKor.setText(String.valueOf(evekOsszegzese("F")));
//                jLMiotaDolgozik.setText(String.valueOf(kereses("F")));
//                mentettAdatok+="legidősebb:"+jLLegidosebb.getText()+" éves\n";
//                mentettAdatok+="ÖsszesKor"+jLOsszKor.getText()+" ev\n";
//                mentettAdatok+="6 éve dolgozó:"+jLMiotaDolgozik.getText();
//                
//                mentettAdatok+="legidősebb:"+legidosebb("F")+" éves\n";
//                mentettAdatok+="ÖsszesKor"+evekOsszegzese("F")+" ev\n";
//                mentettAdatok+="6 éve dolgozó:"+kereses("F");
adatKiiras("F");

            
        }
        else{
            String nem="";
            if(jRBL.isSelected()){
                mentettAdatok+="Lányok:\n";
                nem="L";
                adatKiiras(nem);
            }
            else{
                mentettAdatok+="Fiuk:\n";
                nem="F";
                adatKiiras(nem);
                
            }
//            jLLegidosebb.setText(String.valueOf(legidosebb(nem))); 
//            jLOsszKor.setText(String.valueOf(evekOsszegzese(nem)));
//            jLMiotaDolgozik.setText(String.valueOf(kereses(nem)));
//            mentettAdatok+="legidősebb:"+jLLegidosebb.getText()+" éves\n";
//            mentettAdatok+="ÖsszesKor"+jLOsszKor.getText()+" ev\n";
//            mentettAdatok+="6 éve dolgozó:"+jLMiotaDolgozik.getText();
            
//            mentettAdatok+="legidősebb:"+legidosebb(nem)+" éves\n";
//            mentettAdatok+="ÖsszesKor"+evekOsszegzese(nem)+" ev\n";
//            mentettAdatok+="6 éve dolgozó:"+kereses(nem);
        }
        
         mentettAdatok+="\n";
        System.out.println(mentettAdatok);
        FileWriter wr;
        try {
            wr = new FileWriter("dolgozok.txt");
            wr.write(mentettAdatok);
            wr.close();
        } catch (IOException ex) {
            Logger.getLogger(Adatok.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void adatKiiras(String nem){
//            String mentettAdatok="";

            mentettAdatok+="legidősebb:"+legidosebb(nem)+" éves\n";
            mentettAdatok+="ÖsszesKor"+evekOsszegzese(nem)+" ev\n";
            mentettAdatok+="6 éve dolgozó:"+kereses(nem);
    }
    
    private void jRBLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBLActionPerformed
        jLLegidosebb.setText(String.valueOf(legidosebb("L")));
        jLOsszKor.setText(String.valueOf(evekOsszegzese("L")));
        jLMiotaDolgozik.setText(String.valueOf(kereses("L")));
    }//GEN-LAST:event_jRBLActionPerformed

    private void jRBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBFActionPerformed
      jLLegidosebb.setText(String.valueOf(legidosebb("F"))); 
      jLOsszKor.setText(String.valueOf(evekOsszegzese("F")));
      jLMiotaDolgozik.setText(String.valueOf(kereses("F")));
    }//GEN-LAST:event_jRBFActionPerformed

    private void jCBFiukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBFiukActionPerformed
        nevKereses(jCBFiuk.getSelectedItem().toString());
    }//GEN-LAST:event_jCBFiukActionPerformed

    public int legidosebb(String nem) {
        //int max = emberosztaly.get(0).getKor(); Összes közül nézve nem érdemes 0-val kezdeni
        //Csoportosítás alapjám 0-val kezdhetünk
        int max=0;
        for (int i = 0; i < emberosztaly.size(); i++) {
            if (emberosztaly.get(i).getNem().equals(nem)) {
                if (emberosztaly.get(i).getKor() > max) {
                    max = emberosztaly.get(i).getKor();
                }
            }
        }
        return max;
    }
    
    public void legidosebb2(String nem) {
        //int max = emberosztaly.get(0).getKor(); Összes közül nézve nem érdemes 0-val kezdeni
        //Csoportosítás alapjám 0-val kezdhetünk
        int max=0;
        
        for (int i = 0; i < emberosztaly.size(); i++) {
            if (emberosztaly.get(i).getNem().equals(nem)) {
                if (emberosztaly.get(i).getKor() > max) {
                    max = emberosztaly.get(i).getKor();
                }
            }
        }
        jLLegidosebb.setText(String.valueOf(max));
    }
    
    public int evekOsszegzese(String nem){
        int ev=0;
        for (int i = 0; i < emberosztaly.size(); i++) {
            if (emberosztaly.get(i).getNem().equals(nem)) {
                ev=emberosztaly.get(i).getKor()+ev;
            }
        }
        return ev;
    }
    
    public void evekOsszegzese2(String nem){
        int ev=0;
        for (int i = 0; i < emberosztaly.size(); i++) {
            if (emberosztaly.get(i).getNem().equals(nem)) {
                ev=emberosztaly.get(i).getKor()+ev;
            }
        }
        jLOsszKor.setText(String.valueOf(ev));
    }
    
    public String kereses(String nem){
        String nev="";
        for (int i = 0; i < emberosztaly.size(); i++) {
            if (emberosztaly.get(i).getNem().equals(nem)) {
                if (emberosztaly.get(i).getMnkaToltottEvek()>6) {
                    nev+=emberosztaly.get(i).getNev()+";";
                }
            }
        }
        return nev;
    }
    
     public void kereses2(String nem){
        String nev="";
//        int db=0;
        for (int i = 0; i < emberosztaly.size(); i++) {
            if (emberosztaly.get(i).getNem().equals(nem)) {
                if (emberosztaly.get(i).getMnkaToltottEvek()>6) {
//                    if (db>0) {
//                      nev+=";";  
//                    }
//                    nev+=emberosztaly.get(i).getNev();
                    nev+=emberosztaly.get(i).getNev()+";";
                }
            }
        }
         jLMiotaDolgozik.setText(nev);
    }
    
    public void osszKiIras(String nem) {
        int max=0;
        int ev=0;
        String nev="";
        for (int i = 0; i < emberosztaly.size(); i++) {
            if (emberosztaly.get(i).getNem().equals(nem)) {
                if (emberosztaly.get(i).getKor() > max) {
                    max = emberosztaly.get(i).getKor();
                }
                 ev=emberosztaly.get(i).getKor()+ev;
                 //ev+=emberosztaly.get(i).getKor();
                 
                 if (emberosztaly.get(i).getMnkaToltottEvek()>6) {
                    nev+=emberosztaly.get(i).getNev()+";";
                }
            }
        }
        jLLegidosebb.setText(String.valueOf(max));
        jLOsszKor.setText(String.valueOf(ev));
        jLMiotaDolgozik.setText(nev);
    }
    
     public void nevKereses(String nev){
        for (int i = 0; i < emberosztaly.size(); i++) {
            if (emberosztaly.get(i).getNev().equals(nev)) {
                jLKor.setText(String.valueOf(emberosztaly.get(i).getKor()));
                jLDolgozik.setText(String.valueOf(emberosztaly.get(i).getMnkaToltottEvek()));
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adatok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adatok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adatok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adatok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adatok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBFiuk;
    private javax.swing.JComboBox<String> jCBLanyok;
    private javax.swing.JCheckBox jCBMindkettoNem;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLDolgozik;
    private javax.swing.JLabel jLKor;
    private javax.swing.JLabel jLLegidosebb;
    private javax.swing.JLabel jLMiotaDolgozik;
    private javax.swing.JLabel jLOsszKor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRBF;
    private javax.swing.JRadioButton jRBL;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
